image: node:latest

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

variables:
  CI: 'true'

before_script:
  - yarn install

stages:
  - test 
  - build

lint:
  stage: test 
  script:
    - yarn lint

build:
  stage: build
  script:
    - yarn build
  artifacts:
    expire_in: '1 week'
    paths:
      - public/
