image: node:latest

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

variables:
  CI: 'true'

before_script:
  - npm ci

stages:
  - test 
  - build

lint:
  stage: test 
  script:
    - npm run lint
    - npm run lint:text

build:
  stage: build
  script:
    - npm run build
  artifacts:
    expire_in: '1 week'
    paths:
      - public/
